version: "3.9"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clearbudget
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - clearbudget-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - clearbudget-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 5s
      timeout: 10s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - clearbudget-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 10s
      retries: 20

  categories-service:
    build:
      context: .
      dockerfile: src/CategoriesService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - clearbudget-net

  transactions-service:
    build:
      context: .
      dockerfile: src/TransactionsService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - clearbudget-net

  reporting-service:
    build:
      context: .
      dockerfile: src/ReportingService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - transactions-service
    networks:
      - clearbudget-net

  gateway:
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    ports:
      - "8081:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - categories-service
      - transactions-service
      - reporting-service
    networks:
      - clearbudget-net

  terraform:
    build:
      context: ./infra/docker/terraform-runner
    volumes:
      - ./infra:/infra
    env_file:
      - .env.terraform
    networks:
      - clearbudget-net
    depends_on:
      keycloak:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: "no"

volumes:
  postgres-data:

networks:
  clearbudget-net:
    driver: bridge
