version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - clearbudget-net

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clearbudget
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - clearbudget-net

  categories-service:
    build:
      context: .
      dockerfile: src/CategoriesService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__Default: "Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=clearbudget"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Port: "5672"
      RabbitMQ__User: "user"
      RabbitMQ__Password: "password"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - clearbudget-net

  transactions-service:
    build:
      context: .
      dockerfile: src/TransactionsService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__Default: "Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=clearbudget"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Port: "5672"
      RabbitMQ__User: "user"
      RabbitMQ__Password: "password"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - clearbudget-net

  reporting-service:
    build:
      context: .
      dockerfile: src/ReportingService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      TransactionsService__BaseUrl: "http://transactions-service"
    depends_on:
      - transactions-service
    networks:
      - clearbudget-net

  gateway:
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "8080:80"
    depends_on:
      - categories-service
      - transactions-service
      - reporting-service
    networks:
      - clearbudget-net

volumes:
  postgres-data:

networks:
  clearbudget-net:
    driver: bridge
