name: 🧪 Unit Tests - CategoriesService by class

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: 📦 Restore dependencies
        run: dotnet restore src/Clear-Budget-API.sln

      - name: 🏗️ Build solution
        run: dotnet build src/Clear-Budget-API.sln --no-restore --configuration Release

      - name: 🔍 Run CategoriesServiceTests
        run: dotnet test src/CategoriesService.Tests/CategoriesService.Tests.csproj --no-build --configuration Release --filter FullyQualifiedName~CategoriesServiceTests
